name: allure-report

on:
  release:
    types:
      - created
  push:
    branches-ignore:
      - '!master'

jobs:
  allure:
    name: Generate Allure Report
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps --force

      - name: Run Playwright Tests
        run: npx playwright test

      - name: Get Allure History
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Copy Allure Results
        run: mkdir -p allure-history && cp -r allure-results/* allure-history/

      - name: Generate Allure Report
        run: npx allure generate allure-history --clean -o allure-report

      - name: Deploy Report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-report

      - name: Push Report to Other Branch
        if: always()
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git checkout -b report
          git add allure-report
          git commit -m "Add Allure report"
          git push origin report --force

      - name: Debug Info
        run: env

